spring.application.name=orderservice
server.port=8082
user.service.base-url=http://localhost:8081
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.retry.instances.paymentService.max-attempts=3
resilience4j.retry.instances.paymentService.wait-duration=2s
resilience4j.retry.instances.paymentService.retry-exceptions=org.springframework.web.client.HttpServerErrorException

# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5

# Open circuit when 50% or more calls fail
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50

# Stay OPEN for 10 seconds
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s

# Number of test calls allowed in HALF_OPEN
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3

# config server address later we can make it as eureka client no harcoded address
spring.config.import=optional:configserver:http://localhost:8888

#spring.profiles.active=dev

# TimeLimiter
resilience4j.timelimiter.instances.paymentService.timeout-duration=3s